CREATE TABLE "frontend_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "frontend_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "frontend_conversation" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "frontend_file" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"url" varchar(1024) NOT NULL,
	"key" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"conversationId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "frontend_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "frontend_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "frontend_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "frontend_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "frontend_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "frontend_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "frontend_account" ADD CONSTRAINT "frontend_account_userId_frontend_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."frontend_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_conversation" ADD CONSTRAINT "frontend_conversation_userId_frontend_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."frontend_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_file" ADD CONSTRAINT "frontend_file_conversationId_frontend_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."frontend_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_post" ADD CONSTRAINT "frontend_post_createdById_frontend_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."frontend_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_session" ADD CONSTRAINT "frontend_session_userId_frontend_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."frontend_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "frontend_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "conversation_user_id_idx" ON "frontend_conversation" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "file_conversation_id_idx" ON "frontend_file" USING btree ("conversationId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "frontend_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "frontend_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "frontend_session" USING btree ("userId");